INSERT INTO GREEN (GREEN_ID, NAME, WATER_DAY_MM) VALUES (1, 'HOME', '100');
INSERT INTO GREEN (GREEN_ID, NAME, WATER_DAY_MM) VALUES (2, 'HOME', '50');
INSERT INTO GREEN (GREEN_ID, NAME, WATER_DAY_MM) VALUES (3, 'HOME', '10');
