spring.cloud.stream:
  function:
    definition: streamApp
  bindings:
    streamApp-in-0:
      destination: input-stream
    streamApp-out-0:
      destination: output-stream
  kafka:
    bindings:
      streamApp-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.StringDeserializer
      streamApp-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.StringSerializer
    binder:
      brokers:
        - localhost:9091
