spring.cloud.stream:
  function:
    definition: streamApp;streamApp2
  bindings:
    streamApp-in-0:
      destination: history
    streamApp-out-0:
      destination: hourly
    streamApp2-in-0:
      destination: hourly
    streamApp2-out-0:
      destination: daily
  kafka:
    bindings:
      streamApp-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      streamApp-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
      streamApp2-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      streamApp2-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
      brokers:
        - localhost:9091
