
# Get current weather of Weinheim
# lat=49.5450 latitude
# lon=8.6603 longitude
# dt=1636287136 UNIXTIME
# appid= >> APIKEY
GET https://api.openweathermap.org/data/2.5/onecall?lat=49.5450&lon=8.6603&exclude=hourly,minutely&appid=??? HTTP/1.1
